apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: rynplynch/frontend:latest
        ports:
        - containerPort: 5000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   selector:
#     app: frontend 
#   ports:
#     - protocol: TCP
#       port: 5000

kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30000
  selector:
    app: frontend

